### ISSUE TITLE
is:issue is:open can you share the db schema , you can see setting ..

### ISSUE THREAD

**Issue by bigrender** [Xyphyn/Imagi#27]
I need to db schiema for pocketbase

**Comment by Xyphyn** [comment]
I'd prefer not to share it, as the typings should give you enough information to reverse engineer, and if I post the schema there may be an unknown vulnerability.

**Comment by Xyphyn** [comment]
https://github.com/Xyphyn/Imagi/blob/5a3c21a91cc6d77d72ffa10c70fa753213e61ec3/src/lib/types/pb-types.ts#L2

^ The typings are here.
